project_name: flog

builds:
  - binary: flog
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - Update README.md
    - Merge pull request
    - Merge branch

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: mingrammer
    name: flog
  name_template: '{{.Tag}}'

